DEV-3737 More uv migration

diff --git a/bin/package b/bin/package
--- a/bin/package
+++ b/bin/package
@@ -1,13 +1,5 @@
 #!/usr/bin/env bash
-
 set -euox pipefail
-
-function cleanup() {
-    # get rid of the virtualenv
-    echo "Cleaning up"
-    deactivate
-    rm -rf "${VENV_NAME:?}/" build/ dist/ include/ local/ share/ gdc-client.spec
-}
 
 function compress() {
     # this way it's cross platform
@@ -24,76 +16,35 @@ with ZipFile('${zip_name}', 'w') as z:
 
 while getopts ":d" opt; do
     case $opt in
-        d)
-            DATE=$(date "+%m_%d_%Y")
-            ;;
-        \?)
-            echo "Invalid option: -$OPTARG" >&2
-            ;;
-	esac
+        d) DATE=$(date "+%m_%d_%Y") ;;
+        \?) echo "Invalid option: -$OPTARG" >&2 ;;
+    esac
 done
 
 DATE=${DATE-} # if date is not passed in, default DATE variable to empty string
-VENV_NAME="venv"
 BINARY_NAME="gdc-client"
-VENV_PATH="$VENV_NAME/bin/activate"
 
-case $(uname -s) in
-    *NT*)
-        # for use in git bash with all the nice unix utilities
-        TARGET_ENVIRONMENT="Windows"
-        BINARY_NAME="gdc-client.exe"
-
-        #  this works in git bash
-        alias python="winpty python"
-
-        # why does windows have to be so different?
-        VENV_PATH="$VENV_NAME/Scripts/activate"
-
-        # Presumably Python3 is the only `python` in the Windows %PATH% variable
-        python -m virtualenv "$VENV_NAME"
-        source "$VENV_PATH"
-        pip install pywin32
-        ;;
-    *Linux*)
-        TARGET_ENVIRONMENT="Ubuntu"
-        python -m virtualenv "$VENV_NAME" --python=python3
-        source "$VENV_PATH"
-        ;;
-    *Darwin*)
-        TARGET_ENVIRONMENT="OSX"
-        python -m virtualenv "$VENV_NAME" --python=python3
-        source "$VENV_PATH"
-        ;;
+case "$(uname -s)" in
+    *NT*) TARGET_ENVIRONMENT="Windows"; BINARY_NAME="gdc-client.exe" ;;
+    *Linux*) TARGET_ENVIRONMENT="Ubuntu" ;;
+    *Darwin*) TARGET_ENVIRONMENT="OSX" ;;
+    *) echo "Unsupported OS"; exit 1 ;;
 esac
 
 # setup.py is in previous dir
 cd ..
 
-python -m pip install --upgrade pip
-python -m pip install --no-deps -r requirements.txt
-python -m pip install --no-deps .
+uv sync --locked --extra dev
 
-# go back go the ./gdc_client/bin dir
 cd bin
 
 echo "Building for ${TARGET_ENVIRONMENT}..."
-
-# Make sure the correct version of pyinstaller and setuptools are installed
-pip install -U PyInstaller
-
-# Ran into ModuleNotFoundError: No module named 'pkg_resources.py2_warn' with higher versions of setuptools
-pip install --upgrade setuptools
-
 # Get version
-VERSION=$(python -c "
+VERSION=$(uv run python -c "
 import gdc_client.version
 print(gdc_client.version.__version__)")
 
-echo "Creating ${TARGET_ENVIRONMENT} package for version ${VERSION}..."
-
-# Create binary
-pyinstaller \
+uv run --with pyinstaller pyinstaller \
     --clean \
     --additional-hooks-dir=. \
     --noconfirm \
@@ -118,7 +69,3 @@ ZIP_NAME="$PRE_ZIP_NAME.zip"
 echo "The output zip file will be called ${ZIP_NAME}"
 compress "$ZIP_NAME" "$BINARY_NAME"
 mv "$ZIP_NAME" ..
-cd ..
-
-cleanup
-export GDC_CLIENT_ZIP="$PRE_ZIP_NAME"
